name: magic8ball
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
  - images/ball1.png
  - images/ball2.png
  - images/ball3.png
  - images/ball4.png
  - images/ball5.png
